/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Conexion.Conexion;
import Sistema.SistemaCajero;
import com.mysql.jdbc.PreparedStatement;
import java.sql.Connection;
import java.sql.DriverManager;

import javax.swing.JOptionPane;

import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author Kevin
 */
public class Interfaz extends javax.swing.JFrame {
    boolean opcionDepositar = false;
    boolean opcionRetirar = false;
    double nuevaCantidad = 0;
    String nuevoNumero;
    String codigoBd;
    String contraseñaBd;
    double respuesta;
    Integer validacion;
    Integer validacion2;
    
    
   /*  public static final String url="jdbc:mysql://localhost:3306/bdbaniscutp";
        public static final String user="root";
        public static final String contraseña="";
        
        PreparedStatement ps ;
        ResultSet rs;
        
        
        public  static Connection getConnection(){
        Connection con = null;
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con = (Connection) DriverManager.getConnection(url,user,contraseña);
        }catch(Exception e){
            System.out.println(e);
        }
        return con;
    }*/
    
    
    
   
    SistemaCajero cajero = new SistemaCajero();
    

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        textoContraseña.setText(" ");
        textoCodigo.setText(" ");
        textoCantidad.setText(" ");
        panelOpcion.setVisible(true);
        botonDepositar.setEnabled(false);
        botonRetirar.setEnabled(false);
        botonSalir.setEnabled(false);
        
        botonNumero1.setEnabled(false);
        botonNumero2.setEnabled(false);
        botonNumero3.setEnabled(false);
        botonNumero4.setEnabled(false);
        botonNumero5.setEnabled(false);
        botonNumero6.setEnabled(false);
        botonNumero7.setEnabled(false);
        botonNumero8.setEnabled(false);
        botonNumero9.setEnabled(false);
        botonNumero0.setEnabled(false);
        
        botonAceptar.setEnabled(false);
        botonBorrar.setEnabled(false);
        botonCancelar.setEnabled(false);
        
        botonConsultarSaldo.setEnabled(false);
        //cajero.contador();
        textoContador.setText(cajero.contador().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonDepositar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        botonSalir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        botonNumero1 = new javax.swing.JButton();
        botonNumero2 = new javax.swing.JButton();
        botonNumero3 = new javax.swing.JButton();
        botonNumero4 = new javax.swing.JButton();
        botonNumero5 = new javax.swing.JButton();
        botonNumero6 = new javax.swing.JButton();
        botonNumero7 = new javax.swing.JButton();
        botonNumero8 = new javax.swing.JButton();
        botonNumero9 = new javax.swing.JButton();
        botonNumero0 = new javax.swing.JButton();
        botonAceptar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        botonBorrar = new javax.swing.JButton();
        botonIngresar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textoContador = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textoCodigo = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        textoSaldo = new javax.swing.JLabel();
        panelOpcion = new javax.swing.JPanel();
        textoOpcion = new javax.swing.JLabel();
        textoCantidad = new javax.swing.JLabel();
        textoContraseña = new javax.swing.JLabel();
        botonRetirar = new javax.swing.JButton();
        botonConsultarSaldo = new javax.swing.JButton();

        botonDepositar.setText("dpositar");
        botonDepositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDepositarActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("SALIR");

        botonSalir.setText("<");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel8.setBackground(new java.awt.Color(153, 153, 153));
        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        botonNumero1.setText("1");
        botonNumero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNumero1ActionPerformed(evt);
            }
        });

        botonNumero2.setText("2");
        botonNumero2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNumero2ActionPerformed(evt);
            }
        });

        botonNumero3.setText("3");
        botonNumero3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNumero3ActionPerformed(evt);
            }
        });

        botonNumero4.setText("4");
        botonNumero4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNumero4ActionPerformed(evt);
            }
        });

        botonNumero5.setText("5");
        botonNumero5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNumero5ActionPerformed(evt);
            }
        });

        botonNumero6.setText("6");
        botonNumero6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNumero6ActionPerformed(evt);
            }
        });

        botonNumero7.setText("7");
        botonNumero7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNumero7ActionPerformed(evt);
            }
        });

        botonNumero8.setText("8");
        botonNumero8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNumero8ActionPerformed(evt);
            }
        });

        botonNumero9.setText("9");
        botonNumero9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNumero9ActionPerformed(evt);
            }
        });

        botonNumero0.setText("0");
        botonNumero0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNumero0ActionPerformed(evt);
            }
        });

        botonAceptar.setBackground(new java.awt.Color(102, 255, 102));
        botonAceptar.setText("ACEPTAR");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        botonCancelar.setBackground(new java.awt.Color(255, 51, 51));
        botonCancelar.setText("CANCELAR");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        jPanel9.setBackground(new java.awt.Color(0, 0, 0));
        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        botonBorrar.setBackground(new java.awt.Color(255, 255, 0));
        botonBorrar.setText("BORRAR");
        botonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(botonNumero4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonNumero5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonNumero6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(botonNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonNumero3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botonNumero0, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(botonNumero7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(botonNumero8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(botonNumero9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonNumero3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonNumero4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonNumero5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonNumero6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonNumero7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonNumero8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonNumero9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(botonNumero0, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        botonIngresar.setBackground(new java.awt.Color(255, 255, 255));
        botonIngresar.setText("INGRESAR");
        botonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIngresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(botonIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel5.setBackground(new java.awt.Color(102, 204, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BANISCUTP");

        textoContador.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        textoContador.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(textoContador, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textoContador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(153, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel7.setBackground(new java.awt.Color(204, 0, 51));
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CONSULTAR");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("RETIRAR");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Usuario:");

        textoCodigo.setForeground(new java.awt.Color(255, 255, 255));
        textoCodigo.setText("Codigo");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Saldo:");

        textoSaldo.setForeground(new java.awt.Color(255, 255, 255));

        panelOpcion.setBackground(new java.awt.Color(204, 0, 51));
        panelOpcion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 2));

        textoOpcion.setForeground(new java.awt.Color(255, 255, 255));
        textoOpcion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoOpcion.setText("OPCION");

        textoCantidad.setForeground(new java.awt.Color(255, 255, 255));
        textoCantidad.setText("CANTIDAD");
        textoCantidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panelOpcionLayout = new javax.swing.GroupLayout(panelOpcion);
        panelOpcion.setLayout(panelOpcionLayout);
        panelOpcionLayout.setHorizontalGroup(
            panelOpcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpcionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelOpcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                    .addComponent(textoOpcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        panelOpcionLayout.setVerticalGroup(
            panelOpcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpcionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoOpcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoCantidad)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        textoContraseña.setBackground(new java.awt.Color(255, 255, 255));
        textoContraseña.setForeground(new java.awt.Color(255, 255, 255));
        textoContraseña.setText("Contraseña: ");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(10, 10, 10)
                        .addComponent(textoSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textoContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(panelOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textoCodigo)
                    .addComponent(textoContraseña))
                .addGap(3, 3, 3)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(textoSaldo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(37, 37, 37))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(panelOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 12, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        botonRetirar.setText("<");
        botonRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRetirarActionPerformed(evt);
            }
        });

        botonConsultarSaldo.setText("<");
        botonConsultarSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultarSaldoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonConsultarSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(botonConsultarSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(botonRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonNumero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNumero1ActionPerformed
        if(textoCantidad.getText().equals(" ")){
            textoCantidad.setText("");
            nuevoNumero = textoCantidad.getText() + "1";
            textoCantidad.setText(nuevoNumero);

        }
        else{
            nuevoNumero = textoCantidad.getText() + "1";
            textoCantidad.setText(nuevoNumero);
        }
    }//GEN-LAST:event_botonNumero1ActionPerformed

    private void botonNumero2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNumero2ActionPerformed
        if(textoCantidad.getText().equals(" ")){
            textoCantidad.setText("");
            nuevoNumero = textoCantidad.getText() + "2";
            textoCantidad.setText(nuevoNumero);

        }
        else{
            nuevoNumero = textoCantidad.getText() + "2";
            textoCantidad.setText(nuevoNumero);
        }
    }//GEN-LAST:event_botonNumero2ActionPerformed

    private void botonNumero3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNumero3ActionPerformed
        if(textoCantidad.getText().equals(" ")){
            textoCantidad.setText("");
            nuevoNumero = textoCantidad.getText() + "3";
            textoCantidad.setText(nuevoNumero);

        }
        else{
            nuevoNumero = textoCantidad.getText() + "3";
            textoCantidad.setText(nuevoNumero);
        }
    }//GEN-LAST:event_botonNumero3ActionPerformed

    private void botonNumero4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNumero4ActionPerformed
        if(textoCantidad.getText().equals(" ")){
            textoCantidad.setText("");
            nuevoNumero = textoCantidad.getText() + "4";
            textoCantidad.setText(nuevoNumero);

        }
        else{
            nuevoNumero = textoCantidad.getText() + "4";
            textoCantidad.setText(nuevoNumero);
        }
    }//GEN-LAST:event_botonNumero4ActionPerformed

    private void botonNumero5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNumero5ActionPerformed
        if(textoCantidad.getText().equals(" ")){
            textoCantidad.setText("");
            nuevoNumero = textoCantidad.getText() + "5";
            textoCantidad.setText(nuevoNumero);

        }
        else{
            nuevoNumero = textoCantidad.getText() + "5";
            textoCantidad.setText(nuevoNumero);
        }
    }//GEN-LAST:event_botonNumero5ActionPerformed

    private void botonNumero6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNumero6ActionPerformed
        if(textoCantidad.getText().equals(" ")){
            textoCantidad.setText("");
            nuevoNumero = textoCantidad.getText() + "6";
            textoCantidad.setText(nuevoNumero);

        }
        else{
            nuevoNumero = textoCantidad.getText() + "6";
            textoCantidad.setText(nuevoNumero);
        }
    }//GEN-LAST:event_botonNumero6ActionPerformed

    private void botonNumero7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNumero7ActionPerformed
        if(textoCantidad.getText().equals(" ")){
            textoCantidad.setText("");
            nuevoNumero = textoCantidad.getText() + "7";
            textoCantidad.setText(nuevoNumero);

        }
        else{
            nuevoNumero = textoCantidad.getText() + "7";
            textoCantidad.setText(nuevoNumero);
        }
    }//GEN-LAST:event_botonNumero7ActionPerformed

    private void botonNumero8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNumero8ActionPerformed
        if(textoCantidad.getText().equals(" ")){
            textoCantidad.setText("");
            nuevoNumero = textoCantidad.getText() + "8";
            textoCantidad.setText(nuevoNumero);

        }
        else{
            nuevoNumero = textoCantidad.getText() + "8";
            textoCantidad.setText(nuevoNumero);
        }
    }//GEN-LAST:event_botonNumero8ActionPerformed

    private void botonNumero9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNumero9ActionPerformed
        if(textoCantidad.getText().equals(" ")){
            textoCantidad.setText("");
            nuevoNumero = textoCantidad.getText() + "9";
            textoCantidad.setText(nuevoNumero);

        }
        else{
            nuevoNumero = textoCantidad.getText() + "9";
            textoCantidad.setText(nuevoNumero);
        }
    }//GEN-LAST:event_botonNumero9ActionPerformed

    private void botonNumero0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNumero0ActionPerformed
        if(textoCantidad.getText().equals(" ")){
            textoCantidad.setText("");
            nuevoNumero = textoCantidad.getText() + "0";
            textoCantidad.setText(nuevoNumero);

        }
        else{
            nuevoNumero = textoCantidad.getText() + "0";
            textoCantidad.setText(nuevoNumero);
        }
    }//GEN-LAST:event_botonNumero0ActionPerformed

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        Double cajeroCantidad;
        textoContraseña.setText(" ");
        if(textoCantidad.getText().equals(" ")){
            opcionDepositar = false;
            opcionRetirar = false;

            panelOpcion.setVisible(true);
            botonDepositar.setEnabled(true);
            botonRetirar.setEnabled(true);
            textoCantidad.setText(" ");

            botonNumero1.setEnabled(false);
            botonNumero2.setEnabled(false);
            botonNumero3.setEnabled(false);
            botonNumero4.setEnabled(false);
            botonNumero5.setEnabled(false);
            botonNumero6.setEnabled(false);
            botonNumero7.setEnabled(false);
            botonNumero8.setEnabled(false);
            botonNumero9.setEnabled(false);
            botonNumero0.setEnabled(false);

            botonCancelar.setEnabled(false);
            botonBorrar.setEnabled(false);
            botonAceptar.setEnabled(false);

        }
        else{
            if(opcionDepositar == true){
                opcionDepositar=false;
               

                nuevaCantidad = Double.parseDouble(String.valueOf(textoCantidad.getText()));
                cajero.depositar(nuevaCantidad,codigoBd,contraseñaBd);
                

                textoSaldo.setText(String.valueOf(cajero.obtenerSaldo()));
                panelOpcion.setVisible(true);
                textoCantidad.setText(" ");
                botonDepositar.setEnabled(true);
                botonRetirar.setEnabled(true);

                botonNumero1.setEnabled(false);
                botonNumero2.setEnabled(false);
                botonNumero3.setEnabled(false);
                botonNumero4.setEnabled(false);
                botonNumero5.setEnabled(false);
                botonNumero6.setEnabled(false);
                botonNumero7.setEnabled(false);
                botonNumero8.setEnabled(false);
                botonNumero9.setEnabled(false);
                botonNumero0.setEnabled(false);

                botonCancelar.setEnabled(false);
                botonBorrar.setEnabled(false);
                botonAceptar.setEnabled(false);
                
                

            }
            else{
                if(opcionRetirar == true){
                    opcionRetirar=false;

                    nuevaCantidad = Double.parseDouble(String.valueOf(textoCantidad.getText()));
                    cajeroCantidad = cajero.totalCajero(Integer.parseInt(textoContador.getText()));
                    
                    if(nuevaCantidad>2000){
                        
                        if(nuevaCantidad>cajeroCantidad){
                        JOptionPane.showMessageDialog(null, "El cajero no tiene este monto. ");
                        }
                        else{
                            
                        validacion2=cajero.validarCuenta(nuevaCantidad,codigoBd,contraseñaBd);
                        if(validacion2==1){
                        
                            validacion=cajero.validarBilletes(Integer.parseInt(textoContador.getText()), nuevaCantidad);
                            if(validacion == 1){
                            cajero.retirar(nuevaCantidad, codigoBd,contraseñaBd);
                        }
                        else{
                            JOptionPane.showMessageDialog(null, "No se pudo retirar por falta de billetes. ");
                        }
                       }
                        
                        
                        
                        }
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "El cajero solo puede retirar un monto mayor a 2000. ");
                    }
                  
                    
                          
               
                    //textoSaldo.setText(String.valueOf(cajero.obtenerSaldo()));
                    respuesta = cajero.obtenerSaldo();
                    if(respuesta==0){
                        textoCodigo.setText(" ");
                        panelOpcion.setVisible(true);
                        textoCantidad.setText(" ");
                        botonDepositar.setEnabled(false);
                        botonRetirar.setEnabled(false);
                        botonConsultarSaldo.setEnabled(false);
                        botonSalir.setEnabled(false);

                        botonNumero1.setEnabled(false);
                        botonNumero2.setEnabled(false);
                        botonNumero3.setEnabled(false);
                        botonNumero4.setEnabled(false);
                        botonNumero5.setEnabled(false);
                        botonNumero6.setEnabled(false);
                        botonNumero7.setEnabled(false);
                        botonNumero8.setEnabled(false);
                        botonNumero9.setEnabled(false);
                        botonNumero0.setEnabled(false);

                        botonCancelar.setEnabled(false);
                        botonBorrar.setEnabled(false);
                        botonAceptar.setEnabled(false);
                        botonIngresar.setEnabled(true);
                    
                    }
                    else{
                        if(respuesta==-1){
                            textoCodigo.setText(" ");

                            panelOpcion.setVisible(true);
                            textoCantidad.setText(" ");
                            botonDepositar.setEnabled(false);
                            botonRetirar.setEnabled(false);
                            botonConsultarSaldo.setEnabled(false);
                            botonSalir.setEnabled(false);

                            botonNumero1.setEnabled(false);
                            botonNumero2.setEnabled(false);
                            botonNumero3.setEnabled(false);
                            botonNumero4.setEnabled(false);
                            botonNumero5.setEnabled(false);
                            botonNumero6.setEnabled(false);
                            botonNumero7.setEnabled(false);
                            botonNumero8.setEnabled(false);
                            botonNumero9.setEnabled(false);
                            botonNumero0.setEnabled(false);

                            botonCancelar.setEnabled(false);
                            botonBorrar.setEnabled(false);
                            botonAceptar.setEnabled(false);
                            botonIngresar.setEnabled(true);
                        }
                        else{
                            JOptionPane.showMessageDialog(null, "Su nuevo saldo es de: "+respuesta);
                            textoCodigo.setText(" ");

                            panelOpcion.setVisible(true);
                            textoCantidad.setText(" ");
                            botonDepositar.setEnabled(false);
                            botonRetirar.setEnabled(false);
                            botonConsultarSaldo.setEnabled(false);
                            botonSalir.setEnabled(false);

                            botonNumero1.setEnabled(false);
                            botonNumero2.setEnabled(false);
                            botonNumero3.setEnabled(false);
                            botonNumero4.setEnabled(false);
                            botonNumero5.setEnabled(false);
                            botonNumero6.setEnabled(false);
                            botonNumero7.setEnabled(false);
                            botonNumero8.setEnabled(false);
                            botonNumero9.setEnabled(false);
                            botonNumero0.setEnabled(false);

                            botonCancelar.setEnabled(false);
                            botonBorrar.setEnabled(false);
                            botonAceptar.setEnabled(false);
                            botonIngresar.setEnabled(true);
                            
                        }
                        
                    }
                    
                    

                }
            }

        }
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        textoContraseña.setText(" ");
        //textoSaldo.setText(String.valueOf(cajero.obtenerSaldo()));

    }//GEN-LAST:event_botonCancelarActionPerformed

    private void botonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarActionPerformed
        textoContraseña.setText(" ");
        textoCantidad.setText(textoCantidad.getText().substring(0,textoCantidad.getText().length()-1));

        if(textoCantidad.getText().equals("")){
            textoCantidad.setText(" ");

        }
    }//GEN-LAST:event_botonBorrarActionPerformed

    private void botonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIngresarActionPerformed

        
        textoCodigo.setText(JOptionPane.showInputDialog("Ingrese su codigo. "));
        textoContraseña.setText(JOptionPane.showInputDialog("Ingrese su contraseña. "));
        codigoBd=textoCodigo.getText();
        contraseñaBd=textoContraseña.getText();
        textoContraseña.setText(" ");        
        botonIngresar.setEnabled(false);
        botonDepositar.setEnabled(true);
        botonRetirar.setEnabled(true);
        botonSalir.setEnabled(true);   
        botonConsultarSaldo.setEnabled(true);
    }//GEN-LAST:event_botonIngresarActionPerformed

    private void botonDepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDepositarActionPerformed
        textoContraseña.setText(" ");
        opcionDepositar = true;
        botonRetirar.setEnabled(false);
        botonDepositar.setEnabled(false);
        panelOpcion.setVisible(true);
        textoOpcion.setText("Ingrese una cantidad a depositar. ");

        botonNumero1.setEnabled(true);
        botonNumero2.setEnabled(true);
        botonNumero3.setEnabled(true);
        botonNumero4.setEnabled(true);
        botonNumero5.setEnabled(true);
        botonNumero6.setEnabled(true);
        botonNumero7.setEnabled(true);
        botonNumero8.setEnabled(true);
        botonNumero9.setEnabled(true);
        botonNumero0.setEnabled(true);

        botonCancelar.setEnabled(true);
        botonBorrar.setEnabled(true);
        botonAceptar.setEnabled(true);

    }//GEN-LAST:event_botonDepositarActionPerformed

    private void botonRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRetirarActionPerformed
        textoContraseña.setText(" ");
        opcionRetirar = true;
        botonRetirar.setEnabled(false);
        botonDepositar.setEnabled(false);
        panelOpcion.setVisible(true);
        textoOpcion.setText("Ingrese una cantidad a retirar. ");

        botonNumero1.setEnabled(true);
        botonNumero2.setEnabled(true);
        botonNumero3.setEnabled(true);
        botonNumero4.setEnabled(true);
        botonNumero5.setEnabled(true);
        botonNumero6.setEnabled(true);
        botonNumero7.setEnabled(true);
        botonNumero8.setEnabled(true);
        botonNumero9.setEnabled(true);
        botonNumero0.setEnabled(true);

        botonCancelar.setEnabled(true);
        botonBorrar.setEnabled(true);
        botonAceptar.setEnabled(true);

    }//GEN-LAST:event_botonRetirarActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        textoContraseña.setText(" ");
        if(opcionDepositar == true || opcionRetirar == true){
            opcionDepositar = false;
            opcionRetirar = false;

            panelOpcion.setVisible(true);
            botonDepositar.setEnabled(true);
            botonRetirar.setEnabled(true);

            botonNumero1.setEnabled(false);
            botonNumero2.setEnabled(false);
            botonNumero3.setEnabled(false);
            botonNumero4.setEnabled(false);
            botonNumero5.setEnabled(false);
            botonNumero6.setEnabled(false);
            botonNumero7.setEnabled(false);
            botonNumero8.setEnabled(false);
            botonNumero9.setEnabled(false);
            botonNumero0.setEnabled(false);

            botonCancelar.setEnabled(false);
            botonBorrar.setEnabled(false);
            botonAceptar.setEnabled(false);

            textoCantidad.setText(" ");
        }
        else{
            disminuir();
            JOptionPane.showMessageDialog(null, "Se salio del aplicativo. ");
            System.exit(0);
        }
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonConsultarSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultarSaldoActionPerformed
        textoContraseña.setText(" ");   
        cajero.obtenerSaldo2(codigoBd, contraseñaBd);
        
        respuesta = cajero.obtenerSaldo();
        textoSaldo.setText(" ");
        
        if(respuesta==0){
            botonConsultarSaldo.setEnabled(false);
            botonIngresar.setEnabled(true);
            botonDepositar.setEnabled(false);
            botonRetirar.setEnabled(false);
            botonSalir.setEnabled(false);
            textoCodigo.setText(" ");
        }
        else{
            JOptionPane.showMessageDialog(null, "Su saldo es de: "+respuesta);
            botonConsultarSaldo.setEnabled(false);
            botonIngresar.setEnabled(true);
            botonDepositar.setEnabled(false);
            botonRetirar.setEnabled(false);
            botonSalir.setEnabled(false);
            textoCodigo.setText(" ");
        }
        
      
    }//GEN-LAST:event_botonConsultarSaldoActionPerformed

    public void disminuir(){
        int numero=Integer.parseInt(textoContador.getText());
        if(numero>1){
            cajero.actualizarContador(numero-1);
        }
        else{
            cajero.actualizarContador(1);
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        Interfaz inter=new Interfaz();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                inter.setVisible(true);
                inter.setLocationRelativeTo(null);
                   
             
            }
               
        });
        
        //inter.disminuir();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonBorrar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonConsultarSaldo;
    private javax.swing.JButton botonDepositar;
    private javax.swing.JButton botonIngresar;
    private javax.swing.JButton botonNumero0;
    private javax.swing.JButton botonNumero1;
    private javax.swing.JButton botonNumero2;
    private javax.swing.JButton botonNumero3;
    private javax.swing.JButton botonNumero4;
    private javax.swing.JButton botonNumero5;
    private javax.swing.JButton botonNumero6;
    private javax.swing.JButton botonNumero7;
    private javax.swing.JButton botonNumero8;
    private javax.swing.JButton botonNumero9;
    private javax.swing.JButton botonRetirar;
    private javax.swing.JButton botonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel panelOpcion;
    private javax.swing.JLabel textoCantidad;
    private javax.swing.JLabel textoCodigo;
    private javax.swing.JLabel textoContador;
    private javax.swing.JLabel textoContraseña;
    private javax.swing.JLabel textoOpcion;
    private javax.swing.JLabel textoSaldo;
    // End of variables declaration//GEN-END:variables
}
